trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps: 
    - bash: echo Build FisrtJob
  - job: SecondJob
    steps: 
    - bash: echo Build SecondJob
    - bash: echo $(PipelineLevelVariable)

- stage: DevDeploy
  variables:
    environment: Dev
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps: 
    - bash: echo $(environment)DevDeployJob

- stage: QADeploy
  variables:
    environment: QA
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps: 
    - bash: echo $(environment)QADeployJob

- stage: ProdDeploy
  variables:
    environment: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdDeployJob
    steps: 
    - bash: echo $(environment)ProdDeployJob

